[2024-03-23T21:00:17.911-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks3.task_C scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-23T21:00:17.916-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks3.task_C scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-23T21:00:17.916-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-03-23T21:00:17.916-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-03-23T21:00:17.916-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-03-23T21:00:17.928-0300] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): task_C> on 2024-03-23 00:00:00+00:00
[2024-03-23T21:00:17.929-0300] {standard_task_runner.py:55} INFO - Started process 7525 to run task
[2024-03-23T21:00:17.931-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks3', 'task_C', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/multiple_tasks3.py', '--cfg-path', '/tmp/tmp6pp97x_s']
[2024-03-23T21:00:17.931-0300] {standard_task_runner.py:83} INFO - Job 107: Subtask task_C
[2024-03-23T21:00:17.965-0300] {task_command.py:389} INFO - Running <TaskInstance: executing_multiple_tasks3.task_C scheduled__2024-03-23T00:00:00+00:00 [running]> on host DESKTOP-0DNP0LN.localdomain
[2024-03-23T21:00:18.006-0300] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=falcone
AIRFLOW_CTX_DAG_ID=executing_multiple_tasks3
AIRFLOW_CTX_TASK_ID=task_C
AIRFLOW_CTX_EXECUTION_DATE=2024-03-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-23T00:00:00+00:00
[2024-03-23T21:00:18.006-0300] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-03-23T21:00:18.006-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Task C has started!\nsleep 3\n# task will fail when using exit 99\nexit 130\necho Task C has ended!']
[2024-03-23T21:00:18.009-0300] {subprocess.py:86} INFO - Output:
[2024-03-23T21:00:18.009-0300] {subprocess.py:93} INFO - Task C has started!
[2024-03-23T21:00:21.010-0300] {subprocess.py:97} INFO - Command exited with return code 130
[2024-03-23T21:00:21.015-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/carlosfalcone/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2024-03-23T21:00:21.017-0300] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks3, task_id=task_C, execution_date=20240323T000000, start_date=20240324T000017, end_date=20240324T000021
[2024-03-23T21:00:21.029-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 107 for task task_C (Bash command failed. The command returned a non-zero exit code 130.; 7525)
[2024-03-23T21:00:21.044-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-03-23T21:00:21.056-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
